### PR TITLE
Added "timezone" endpoint

### PR DESCRIPTION
**Pull request by kehollin**
Added the "timezone" endpoint to look up extended time zone information
by lat/lon. Added tests to match existing endpoints and data models.
Also added data model tests for my prior submission (didn't notice the
other model tests, sorry).

### CODE REVIEW

**Comment by kehollin** [comment]
Thanks!

Kevin Hollingshead
Research Software Engineer

_Arizona State University_
_College of Health Solutions_
_School of Nutrition and Health Promotion_
602-615-9972 (cell)

**Comment by danludwig** [comment]
No, thank you. Wish I had time to make a new nuget package for this. Would you be interested in taking over this repo officially? I don't use it any more.

**Comment by kehollin** [comment]
It was a pleasure, lots of stuff I'd never seen before. I think I'll take a
pass on management at this point, but thanks. I've got a seriously full
plate trying to keep hungry researchers supplied with data.

I do thank you sincerely for the amazingly thorough job you did with this,
your Karma is in the black fer sure. :)

Kevin Hollingshead
Research Software Engineer

_Arizona State University_
_College of Health Solutions_
_School of Nutrition and Health Promotion_
602-615-9972 (cell)

**Comment by danludwig** [comment]
:+1:

**Pull request merged**
